#!/bin/bash

# Sprint 6 - RBAC Implementation Deployment Commands
# Execute these commands in order to deploy Sprint 6

echo "============================"
echo "Sprint 6 Deployment Started"
echo "============================"
echo ""

# Step 1: Git Pull (Download latest changes from GitHub)
echo "Step 1: Pulling latest changes from GitHub..."
echo "Command:"
echo "  git pull origin main"
echo ""
echo "Expected output:"
echo "  - Downloading new files (auditlog.py, user_schema.py, permissions.py, admin.py, guides)"
echo "  - Files updated: X files changed, Y insertions(+), Z deletions(-)"
echo ""
echo ">>>>>> RUN THIS COMMAND <<<<<<"
git pull origin main
echo ""
echo "============================"
echo "Pull completed successfully!"
echo "============================"
echo ""

# Step 2: Docker rebuild (if needed)
echo "Step 2: Rebuild Docker containers..."
echo "Command:"
echo "  docker compose up -d --build"
echo ""
echo "Expected output:"
echo "  - Building backend service"
echo "  - Container ats-ia-backend-1 created/updated"
echo ""
echo ">>>>>> RUN THIS COMMAND <<<<<<"
docker compose up -d --build
echo ""
echo "Wait 5-10 seconds for services to start..."
sleep 10
echo "Done!"
echo ""
echo "============================"
echo ""

# Step 3: Create Alembic migration
echo "Step 3: Creating database migration for AuditLog table..."
echo "Command:"
echo "  docker exec -it ats-ia-backend-1 alembic revision --autogenerate -m \"Add AuditLog table\""
echo ""
echo "Expected output:"
echo "  - Generating migration file in backend/alembic/versions/"
echo "  - File created: xxx_add_auditlog_table.py"
echo ""
echo ">>>>>> RUN THIS COMMAND <<<<<<"
docker exec -it ats-ia-backend-1 alembic revision --autogenerate -m "Add AuditLog table"
echo ""
echo "============================"
echo ""

# Step 4: Run migration
echo "Step 4: Running database migration..."
echo "Command:"
echo "  docker exec -it ats-ia-backend-1 alembic upgrade head"
echo ""
echo "Expected output:"
echo "  - Running migration: xxx_add_auditlog_table.py"
echo "  - Create table \"audit_logs\""
echo "  - Done!"
echo ""
echo ">>>>>> RUN THIS COMMAND <<<<<<"
docker exec -it ats-ia-backend-1 alembic upgrade head
echo ""
echo "============================"
echo ""

# Step 5: Update main.py (manual step)
echo "Step 5: UPDATE MAIN.PY (MANUAL STEP)"
echo ""
echo "You need to manually update: backend/app/main.py"
echo ""
echo "Add these lines after the existing imports:"
echo "  from app.api.v1 import admin"
echo ""
echo "And add this line where other routers are included (around line 40-50):"
echo "  app.include_router(admin.router)"
echo ""
echo "File location: backend/app/main.py"
echo "Then save and the backend will auto-reload."
echo ""
echo "============================"
echo ""

# Step 6: Verify
echo "Step 6: Verify deployment"
echo "Commands:"
echo "  # Check health"
echo "  curl http://localhost:8000/health"
echo ""
echo "  # Check admin endpoint (should fail with 401 if not logged in - that's OK)"
echo "  curl http://localhost:8000/api/v1/admin/users"
echo ""
echo "  # Check Swagger docs"
echo "  open http://localhost:8000/docs"
echo ""
echo "============================"
echo ""
echo "SUCCESS! Sprint 6 deployed."
echo "Files created:"
echo "  - backend/app/models/auditlog.py"
echo "  - backend/app/schemas/user_schema.py"
echo "  - backend/app/core/permissions.py"
echo "  - backend/app/api/v1/admin.py"
echo "  - SPRINT6_GUIDE.md"
echo "  - SPRINT6_COMPLETION_STATUS.md"
echo ""
echo "Database table created:"
echo "  - audit_logs (for tracking actions)"
echo ""
echo "Admin endpoints available:"
echo "  - GET /api/v1/admin/users"
echo "  - GET /api/v1/admin/users/{user_id}"
echo "  - POST /api/v1/admin/users"
echo "  - PATCH /api/v1/admin/users/{user_id}/role"
echo "  - DELETE /api/v1/admin/users/{user_id}"
echo "  - GET /api/v1/admin/audit-logs"
echo ""
echo "============================"
