"""Add AuditLog table

Revision ID: 4b2e42f90015
Revises: d1e2f3a4
Create Date: 2026-01-05 21:48:32.950570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b2e42f90015'
down_revision: Union[str, Sequence[str], None] = 'd1e2f3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_cvs_application_id'), table_name='parsed_cvs')
    op.drop_index(op.f('ix_parsed_cvs_full_name'), table_name='parsed_cvs')
    op.drop_index(op.f('ix_parsed_cvs_id'), table_name='parsed_cvs')
    op.drop_index(op.f('ix_parsed_cvs_matching_score'), table_name='parsed_cvs')
    op.drop_table('parsed_cvs')
    op.drop_index(op.f('idx_applications_candidate_id'), table_name='applications')
    op.drop_index(op.f('idx_applications_offer_id'), table_name='applications')
    op.drop_index(op.f('idx_cv_texts_application_id'), table_name='cv_texts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_cv_texts_application_id'), 'cv_texts', ['application_id'], unique=False)
    op.create_index(op.f('idx_applications_offer_id'), 'applications', ['offer_id'], unique=False)
    op.create_index(op.f('idx_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_table('parsed_cvs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('education', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('languages', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('matching_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('skills_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('experience_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('education_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('language_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=True),
    sa.Column('scoring_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('parsed_cvs_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('parsed_cvs_pkey')),
    sa.UniqueConstraint('application_id', name=op.f('uq_parsed_cvs_application_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_parsed_cvs_matching_score'), 'parsed_cvs', ['matching_score'], unique=False)
    op.create_index(op.f('ix_parsed_cvs_id'), 'parsed_cvs', ['id'], unique=False)
    op.create_index(op.f('ix_parsed_cvs_full_name'), 'parsed_cvs', ['full_name'], unique=False)
    op.create_index(op.f('ix_parsed_cvs_application_id'), 'parsed_cvs', ['application_id'], unique=False)
    # ### end Alembic commands ###
