"""add_scoring_fields_to_offers

Revision ID: f454a6e34948
Revises: 4b2e42f90015
Create Date: 2026-01-09 01:43:56.401233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f454a6e34948'
down_revision: Union[str, Sequence[str], None] = '4b2e42f90015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsed_cvs_application_id'), table_name='parsed_cvs')
    op.drop_index(op.f('ix_parsed_cvs_full_name'), table_name='parsed_cvs')
    op.drop_index(op.f('ix_parsed_cvs_id'), table_name='parsed_cvs')
    op.drop_index(op.f('ix_parsed_cvs_matching_score'), table_name='parsed_cvs')
    op.drop_table('parsed_cvs')
    op.add_column('offers', sa.Column('required_skills', sa.JSON(), nullable=True))
    op.add_column('offers', sa.Column('nice_to_have_skills', sa.JSON(), nullable=True))
    op.add_column('offers', sa.Column('min_experience_years', sa.Integer(), nullable=True))
    op.add_column('offers', sa.Column('required_education', sa.JSON(), nullable=True))
    op.add_column('offers', sa.Column('required_languages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'required_languages')
    op.drop_column('offers', 'required_education')
    op.drop_column('offers', 'min_experience_years')
    op.drop_column('offers', 'nice_to_have_skills')
    op.drop_column('offers', 'required_skills')
    op.create_table('parsed_cvs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('application_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('education', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('languages', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('matching_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('skills_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('experience_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('education_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('language_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scoring_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('parsed_cvs_application_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('parsed_cvs_pkey'))
    )
    op.create_index(op.f('ix_parsed_cvs_matching_score'), 'parsed_cvs', ['matching_score'], unique=False)
    op.create_index(op.f('ix_parsed_cvs_id'), 'parsed_cvs', ['id'], unique=False)
    op.create_index(op.f('ix_parsed_cvs_full_name'), 'parsed_cvs', ['full_name'], unique=False)
    op.create_index(op.f('ix_parsed_cvs_application_id'), 'parsed_cvs', ['application_id'], unique=True)
    # ### end Alembic commands ###
